### ISSUE TITLE
Wann führt die WAWI status_change.pull aus?

### ISSUE THREAD

**Issue by trgaming** [jtl-software/connector-core#10]
Hallo,

bei meinem selbst geschrieben Connector soll der Zahlstatus aus dem Shop geholt werden.

Dazu benutze ich StatusChange. Im Connector-Tester funktioniert das auch, aber die WAWI führt status_change.pull nicht aus?

Kann mir jemand sagen, woran das liegen könnte?

VG, Tim

**Comment by drieschel** [comment]
Hallo @trgaming,

es gibt keinen StatusChange.pull. Es gibt nur einen StatusChange.push.
