### ISSUE TITLE
Frage zu DeliveryNotes

### ISSUE THREAD

**Issue by trgaming** [jtl-software/connector-core#11]
Wenn eine Lieferung in Teilen stattfindet, sendet die WAWI jedes Mal alle Trackingdaten also alle Sendungsverfolgungsnummern oder immer nur die Neuen?

**Comment by drieschel** [comment]
Hallo @trgaming

Hab das Issue gerade erst gesehen, sorry. Bei einer Teillieferung sendet JTL-Wawi die Items der Teillieferung, sowie den Tracking Code, falls einer angegeben wurde. Es gab allerdings zwischenzeitlich einen Bug, wo JTL-Wawi bei einer Teillieferung alle Items der Bestellung gesendet hat. Das wurde aber mittlerweile behoben.
