### ISSUE TITLE
Identities from GlobalDataController::pull are not mapped

### ISSUE THREAD

**Issue by Cangoo** [jtl-software/connector-core#12]
Hi!

I create a CrossSellingGroup in GlobalDataController :: pull:

    class GlobalDataController implements PullInterface, PushInterface
    {
        public function pull(QueryFilter $queryFilter) : array
        {     $result = [];

            $globalData = new GlobalData;

            $crossSellingGroup = (new CrossSellingGroup)
                        ->setId(new Identity("MyCrossSellingShopEndpoint"))
                        ->addI18n((new CrossSellingGroupI18n())->setName("My CrossSellingGroup")->setLanguageIso("de"));

            $globalData->addCrossSellingGroup($crossSellingGroup);
        
            $result[] = $globalData;
            return $result;
        }
        ...
    }

I assumed that this would result in the mapping-table to get an entry with endpoint="MyCrossSellingShopEndpoint", host=[Whatever the host-id is], type=2048 (= IdentityType::CROSS_SELLING_GROUP). In fact in my mapping-class, getHostId is called for this entry, but save is never called, so no entry is created.

The problem with this is that I cannot put products inside my CrossSellingGroups, because the connector can't get any hostId for this:

    $item = (new CrossSellingItem)
        			->setCrossSellingGroupId(new Identity("MyCrossSellingShopEndpoint"));

Looking up the key in the JTL-database manually and hardwiring it into the code makes it work:

    $item = (new CrossSellingItem)
        			->setCrossSellingGroupId(new Identity("MyCrossSellingShopEndpoint"), 1);

Is this a bug or am I missing something?

**Comment by trgaming** [comment]
The Global Data Stuff is only mapped, when you enable "send_all_acks" in the features-matrix.

**Comment by Cangoo** [comment]
Thanks for your reply. "send_all_acks" is set to "true", but it still doesn't work. I helped myself with hardwiring the host-ids in the code (not very "best practices", but I got no other hints or help how to fix this).
