### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by Reflic** [jtl-software/connector-core#17]
Hello all,

we would like to use the (strongly) recommended connector for a new application. However, our entire infrastructure runs on PHP 8.1, I see now that does not work then?

When is support for PHP 8.1 planned? PHP 8.1 is not around since yesterday ;) (November 25, 2021)

**Comment by Platzke-jtl** [comment]
Hi,
please keep comments in English.
Connector Core version 5 supports PHP >=7.2 ([see composer.json](https://github.com/jtl-software/connector-core/blob/master/composer.json#L15)) this includes PHP 8.1 ([semver check](https://jubianchi.github.io/semver-check/#/%3E%3D7.2/8.1)).

We can also confirm that the Core works with 8.1, as we use it in our SaaS Connectors.

**Comment by Reflic** [comment]
hi platzke,

thank you very much. You are right - i did not look good enough. The problem is not jtl\connector itself. It is the dependency `[symfony/http-foundation](https://packagist.org/packages/symfony/http-foundation): ^4.0|^5.0`

We are using Laravel as a framework and this requires a higher version of http-foundation higher than 6.0. Maybe an update would be possible here. I will try bumping the version of http-foundation and will add a pull-request if i am succesful.

**Comment by Platzke-jtl** [comment]
There is already an open discussion about that in #16
