### ISSUE TITLE
How to realize purchase

### ISSUE THREAD

**Issue by Devil-of-Chaos** [jtl-software/connector-core#2]
Is there any documentation ho to create an purchase customer order or anything?

**Comment by drieschel** [comment]
Hello @Devil-of-Chaos,

you are probably looking for the connector documentation (http://docs.jtl-connector.de/en/latest/). You can also check the connector example (https://github.com/jtl-software/connector-example) and the code of some JTL-Connectors here on GitHub, to get a better understanding of how a connector is working.

**Comment by Devil-of-Chaos** [comment]
I Know how the connector is working but our customer needs an purchase feature.
Like a customerOrder width negative quantitiy is this possible. None of the connectores uses such an feature.

**Comment by drieschel** [comment]
Could you explain a bit more detailed what exactly you are looking for? I don't get it.

**Comment by Devil-of-Chaos** [comment]
Our customer is selling new and used products in his onlineshop and is using luwosoft cash system.
But now he wants to integrate an system like rebuy to buy products from customers. But in the connector is nothing explaned about an negative order.

**Comment by drieschel** [comment]
I am afraid, there is no API in JTL-Wawi, where you can create negative orders with.

**Comment by Devil-of-Chaos** [comment]
Is there an way width an batch file or something to usw width an dll. or are there any plans for this?
