### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by pbrainspin** [jtl-software/connector-core#4]
Moin,

i tried to upgrade the PHP version on the server where I run a custom shop with an custom connector integration to PHP 7.4. Everything went fine except that the connector now throws an deprecation exception.

```
Function get_magic_quotes_gpc() is deprecated
```

This seemed strange to me, because my `error_reporting` Variable is set to `E_ALL & ~E_DEPRECATED & ~E_STRICT` in the php.ini. So there should be no deprecated Exception.

After a while I looked a little in your code and noticed that you have these lines in the constructor of your `ErrorHandler`:

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
``` 

These are great values for development, but not so good for production systems. You shouldn't set those values anyway, thats the job of the application using your package. 

I got around this issue by saving the `error_reporting` value before getting the instance of Application and restoring it before running. Something like that:

```php
$connector = Connector::getInstance();
$errorReporting = error_reporting();

$application = Application::getInstance();

error_reporting($errorReporting);

$application->register($connector);
$application->run();
```

It would be great if you could remove the `error_reporting` and `ini_set` calls in a future release or provide a way to replace your default `ErrorHandler` with something else.

thanks

**Comment by drieschel** [comment]
Hello @pbrainspin,

thank you for your effort. You are absolutely right about everything you wrote. It is already possible in the new core which is actual in development (https://github.com/jtl-software/connector-core/tree/develop), to replace the default error handler by your own implementation. We already removed the "display_errors" setting. And we will also remove the "error_reporting" call.

**Comment by drieschel** [comment]
We just released a new core version where the problematic function calls are removed.
